# firestoreのdb設計を書いておく

# ユーザー
users(c):
  documentID(userID == auth.uid) :
    displayName: String
    email: String

# ノート
# notes/:note-id/histories/:hist-id
notes(c):
  documentID(d):
    title: String
    tags: tagRef[]
    editors: userRef[]
    createdAt: Timestamp
    updatedAt: Timestamp

    histories(sub-collection):
      documentID(d):
        user:
          ref: /database/default/documents/users/<uid>,
          name: String

        note:
          ref: /database/default/documents/notes/<uid>

        content: String
        cratedAt: Timestamp

# タグ
tags(c) :
  documentID(d):
    name: String

# コメント
comments(c) :
  documentID(d):
    user: userRef
    note: noteRef
    content: String
    createdAt: Timestamp
